package.json
rest/models/ICompanyNetworkTypeLink.js
rest/models/IDeviceNetworkTypeLink.js
rest/networkProtocols/LoRaOpenSource.js
test.sh
ui/src/views/ImportExport/PullNetworks.js

Had to limit concurrent post connections to 30 or the LoraServer complained about it.
Also fixed test so npm test handles everything.

Pull is golden.

---

.eslintrc.json
config.hjson.unit
package.json
rest/networkProtocols/TheThingsNetwork.js
test/unit/companies.js
test/unit/initializer.js
test/unit/mock-data-api.js
test/unit/mock-server.js
test/unit/networkProtocolDataAccess.js
test/unit/networkProtocols.js
test/unit/networkProviders.js
test/unit/networkTypes.js
test/unit/networks.js
test/unit/protocolData.js
test/unit/ttn-authorization.js
test/unit/users.js

Adds necessary data and processes to handle TTN bearer tokens.
No
Run  npm run unit and verify the output
This only handles User level permissions.  The application level are keys in the applications.
Yes
Eventaully
No
Yes  in test/unit  also mockups of the dao scripts.

Unit test and TTN authorization stuff.

---

rest/networkProtocols/LoRaOpenSource.js
rest/networkProtocols/Loriot.js
rest/networkProtocols/TheThingsNetwork.js

Changes the field names for the protocol handler metadata
no
examine the code for each PH.
Request from UI
Yes
No
No
No

Changed meta field names for protocol handlers.

---

config.hjson.mac
package.json
rest/models/INetworkProtocol.js
rest/restNetworkProtocols.js

Adds meta data to /api/networkProtocols/:id
No
Do a get on url and see metadata
no
Yes
No
No
No

Added meta data to GET /api/networkProtocols/:id

---

rest/models/INetwork.js
rest/networkProtocols/TheThingsNetwork.js
rest/networkProtocols/networkProtocols.js
rest/networkProtocols/networkTypeApi.js

2.  Added authorized flag to networks and set it to false and set it to true on a sucessful connect.
Some bookkeeping on networks
No
Get networks.  Get networkProtocols
To support UI
yes
No
No
No

1.  Added Oauth Information to TTN metadata.

---

package.json
rest/models/IApplication.js
rest/models/INetwork.js
rest/models/INetworkProtocol.js
rest/networkProtocols/networkProtocols.js
rest/restApplications.js
rest/restNetworkProtocols.js
rest/restNetworks.js
test/005-restNetworkProtocols.js
test/007-restNetworks.js
test/013-restApplicationNetworkTypeLinks.js
test/015-launchApplications.js

2.  Updated API Tests to work with new code.
Added searching Network Protocols by Network Type
No specifically.  (See Tests)
Hit the endpoint /api/networkProtocols?networkTypeId=1
No
No
No
No
No
Yes.  I also updated API tests that were failing.  Those need an overhaul in general.

1.  Added networkProtocol query using networkTypeId

---

rest/models/INetwork.js
rest/networkProtocols/Loriot.js
rest/networkProtocols/networkProtocols.js
rest/networkProtocols/networkTypeApi.js
rest/restNetworks.js

2.  Build Test function to verify authentication
Adds Loriot Authentication and Testing
No
Add a Loriot network and use curl/post to /api/networks/{id}/test  and make sure it returns 200 and sucess
Nope
Yes
No
No
No

1.  Setup Loriot for authentication

---

rest/restNetworks.js

Returns a 200 with network on PUT
Returns the network object with POST(201) and PUT (200)
No
POST or PUT network and verify the object is returned. 
No
Yes
No
No
No

Returns a 201 with network on POST

---

rest/networkProtocols/LoRaOpenSource.js
rest/networkProtocols/Loriot.js

Adds /api/networks/{id}/test for LoraOS networks.
No
Not much way yet.  Wait on #81 for full use
Yes
No
No
No

Added Test Endpoint for LoraOS

---

ui/.env
ui/package-lock.json
ui/package.json
ui/src/index.css
ui/src/views/Networks/containers/Network.js
ui/src/views/Networks/views/NetworkProtocolView.js
ui/src/views/Networks/views/NetworkView.js

add tool tips to Network create icons
no
hover over icons in network list view
no
#103 
no
react-tooltip
no

Add tool tips

---

ui/src/utils/protocolUtils.js

Always send authorized flag from front end
A bit of a touchy change, as it hit auth model
Run through the test cases posted in issue #42 
Back end expecting authorized flag from FE in all cases.
#94 
no
no
- Have you added unit or functional tests for this PR
no

always send authorized flag in security data

---

rest/networkProtocols/LoRaOpenSource_2.js
rest/restNetworkProtocols.js

Backs out more complicated (pretty) versioning for functionality with LoraOS2.0
Its a short term fix, so it may be buggy, but it works. 
Create a Lora OS 2.0 network
We are finishing out the plan to make this more user friendly
Yes #101 
Yes
No
No

Undo fancy versioning and just treat 2.0 as a seperate network protocol

---

config.hjson.local

update config.hjson.local to match quick start
no
run through quickstart guide
needs to be merged in order to line up with quickstart guide
n/a
n/a
no
- Does this add new dependencies
no
no

tweak to work for quickstart guide

---

rest/networkProtocols/LoRaOpenSource_2.js
test/e2e/loro-os-2-0-single.js

Also, ran LoraOS2.0 and 1.0 in docker by adding two databases to postgres.
Can run both tests and all pass
E2E test for Lora 2.0 Network
No
Set up Lora in a docker swarm with 2.0 and 1.0 using seperate databases.  
Then run npm run e2e 
Part of the larger e2e effort
yes #117 
Maybe
No
Yes

E2E test for a single Lora 2.0 Network.

---

rest/models/INetwork.js
rest/networkProtocols/Loriot.js
rest/networkProtocols/TheThingsNetwork.js
rest/networkProtocols/networkProtocols.js
test/e2e/ttn-v2-single.js

Like Loriot, Integrations are not in the API but there maybe a way to use the website api. Not sure yet, but all the tests sans integration pass so I am pushing and moving to sync.
E2E for TTN Network
Integrations will need to be dealt with.
npm run e2e
No
Same as Loriot
Yes #120 
Yes
No
Yes

E2E TEsting for TTN Networks

---

rest/networkProtocols/LoRaOpenSource.js
rest/networkProtocols/LoRaOpenSource_2.js
rest/networkProtocols/TheThingsNetwork.js

Adds Username/Password to TTN Protocol Handler Fields. 
No
Look at the code. 
TTN Added Password auth recently which removed the need for the redirect `code` flow used previously. 
Yes #145 
Yes, User Stories
No
Yes

Added Username and Password Fields to TTN Protocol metadata.

---

rest/networkProtocols/LoRaOpenSource.js
rest/networkProtocols/LoRaOpenSource_2.js
rest/networkProtocols/TheThingsNetwork.js

* Fixed Duplicate Service profile in Protocol Database
* Re-tested demo with All 3 networks synched.
See Title
No
Run Demo with V1, V2, and TTN
See slack
Yes #154
No
No
No

* Fixed Bug in TTN denormalize to add LoraV1 devices

---

package-lock.json
package.json
rest/models/INetwork.js
rest/networkProtocols/TheThingsNetwork.js

Refactor some "networks" related functions to use async/await.
No
Run demo
- Have you connected this PR to the issue it resolves? none
- Does the documentation need an update? no
did `npm install request` to ensure request at latest version, to address cryptiles vulnerability.

Small function refactors done for debuggin.

---

rest/lib/appLogger.js
rest/models/IApplication.js
rest/models/INetwork.js
rest/restApplications.js

* Set up uplink data to be dropped if the network is disabled.
Fixed the Network Enable Bug
No
Run Demo and disable/enable a network
Yes #167 
No
No
No

* Fixed enable bug

---

docker/configuration/postgresql/initdb-demo/001-restore-demo.sh
docker/configuration/postgresql/initdb-demo/demo-dump.out
docker/docker-compose-api-test.yml
docker/docker-compose-e2e-test.yml
docker/docker-compose-test.yml
docker/docker-compose.yml

- Adding changes that should have been included in the last PR.  Don't know how they weren't.
- Have you connected this PR to the issue it resolves? #207 

Recommiting lost changes regarding demo data.

---

bin/lib/package.js
bin/package-api-test.js
bin/package-e2e-test.js
bin/package-test.js
bin/package.js
bin/release.js
component-api-test.json
component-e2e-test.json
component-test.json
docs/RELEASE.md

- Add release script to push docker and git tags
- Add release doc to explain release process
Same release process as web-client
- Have you connected this PR to the issue it resolves? None
- Does the documentation need an update? Included
- Have you added unit or functional tests for this PR? No

Add script to run release commands.

---

docker/docker-compose.demo.yml
lpwan2.0/app.js
lpwan2.0/handlers/network-types/lora.js
lpwan2.0/handlers/reporting-protocols/post-handler.js
lpwan2.0/models/application.js
lpwan2.0/models/device-profile.js
lpwan2.0/models/device.js
lpwan2.0/models/network-protocol.js
lpwan2.0/models/network-type.js
lpwan2.0/models/network.js
lpwan2.0/models/reporting-protocol.js
lpwan2.0/package-lock.json
lpwan2.0/package.json

- Add request to package.json
- Use request-promise-native for promised-based fetching
- Authenticate '/users' resource
- Return calls to `next(err)` in models so `res.send` doesn't get called.

Fix small bugs.

---

package-lock.json
package.json
test2.0/mock/ModelAPI-mock.js
test2.0/unit/models/IApplication-test.js
test2.0/unit/models/IDevice-test.js
test2.0/unit/models/IDeviceProfile-test.js
test2.0/unit/models/INetwork-test.js
test2.0/unit/models/IUser-test.js
test2.0/unit/reportingProtocols/reportingProtocols-test.js

Make test coverage recursive
No
Go look at travis
Travis failed because -R is not --recursive 
No
No
No
No

Fixed coverage test

---

rest/networkProtocols/LoRaOpenSource.js

- Populate app name in denormalizeApplicationData for LoRa v1
Most of the bug fixes for this issue were on the front end.
- Have you connected this PR to the issue it resolves? #243 
- Does the documentation need an update? No
- Have you added unit or functional tests for this PR? No

Send name on application update to LoRa v1

---

docker/docker-compose.api-test.yml
docker/docker-compose.demo.yml
docker/docker-compose.e2e-test.yml
docker/docker-compose.loraserver.yml
docker/docker-compose.rest.yml
docker/docker-compose.test.yml
docker/docker-compose.ui.yml
docker/docker-compose.unit-test.yml
docker/docker-compose.yml

- Update all docker-compose file versions to v3
- Have you connected this PR to the issue it resolves? #251 

Update docker-compose files to v3

---

docker/test/e2e/docker-compose.yml
rest/models/IApplication.js
rest/restApplications.js
test2.0/e2e/specs/001-multi-networks.js
test2.0/e2e/specs/008-device-messaging.js
test2.0/lib/helpers.js
test2.0/lib/rc-server.js

- Add app server utility for E2E tests
- Add tests to ensure uplink messages received by LPWAN Server reach the app server
- Test application start/stop and ensure messages are only passed when application is running.
The app server utility caches all requests received and then exposes a method for querying that cache.  In this way the E2E test can check to see if the uplink message reached the app server.
- Have you connected this PR to the issue it resolves? #195 
- Does the documentation need an update? No
- Have you added unit or functional tests for this PR? No

Issue 195 - Test uplink messages

---

docs/install/run.md

- Adds more explicit documentation about DB deploy step when running LPWAN in development.
Forum user omitted deploy step and asked for clarification.
- Have you connected this PR to the issue it resolves? #343 
- Does the documentation need an update? Included

Be explicit about db deploy step in run doc.

---

development/bin/manage-db

- fixes an environment variable typo in a development script
No
View
- Have you connected this PR to the issue it resolves? #342 
- Does the documentation need an update? No
- Have you added unit or functional tests for this PR? Not needed

Update env var typo in script.

---

app/networkProtocols/handlers/LoraOpenSource/v1/metadata.js
app/networkProtocols/handlers/LoraOpenSource/v2/metadata.js
app/networkProtocols/register.js
docs/extensions/existing.md
docs/guides/getting-started.md
docs/install/requirements.md
docs/install/run.md
docs/openapi/api.yml
docs/openapi/dist/api.yml
docs/overview/overview.md
docs/use-cases/multi-type-devices.md
docs/use-cases/pull-network.md
docs/use-cases/transfer-lora-network.md
test/api/run
test/api/tests/005-restNetworkProtocols.js
test/api/tests/007-restNetworks.js
test/api/tests/016-restReportingProtocols.js
test/e2e-https/run
test/e2e-https/tests/multi-type-devices/test.spec.js
test/e2e-https/tests/transfer-lora-network/test.spec.js
test/e2e/run
test/e2e/tests/001-multi-networks.js
test/e2e/tests/008-device-messaging.js

This PR replaces all instances of 'LoRa Server' in the docs with 'ChirpStack'.
No.
Check through the changes to ensure they are happy with all replacements.
Fixes #345 
Yes - #345 
This PR is updating the docs.
No.
Not neccessary.

Replace all instances of LoRa Server with ChirpStack

---

app/models/network-deployment/index.js
app/models/network-protocol/network-deployment-sync.js
app/models/network/index.js
app/networkProtocols/handlers/ChirpStack/ChirpStack.js
app/rest-server/app.js
app/rest-server/handlers/resources/device.js
test/api/tests/003-restUsers.js
test/api/tests/007-restNetworks.js
test/api/tests/008-restApplications.js
test/api/tests/011-restDeviceProfiles.js
test/api/tests/012-restDevices.js
test/api/tests/013-restApplicationNetworkTypeLinks.js
test/api/tests/014-restDeviceNetworkTypeLinks.js
test/api/tests/015-launchApplications.js
test/e2e-https/tests/device-import/test.spec.js
test/e2e-https/tests/multi-type-devices/test.spec.js
test/e2e/tests/004-update-app.js
test/e2e/tests/005-update-device.js
test/e2e/tests/008-device-messaging.js
test/lib/axios-rest-client/index.js
test/lib/rest-client/index.js
test/networks/chirpstack-v1.js
test/networks/chirpstack-v2.js

- Add authentication to uplinks from remote networks
- Have you connected this PR to the issue it resolves? #311 
- Does the documentation need an update? Included
- Have you added unit or functional tests for this PR? Updated

Add authorization header to uplinks

---

app/api.yml
docs/openapi/api.yml
docs/openapi/dist/api.yml
docs/openapi/endpoints/application.yml
docs/openapi/endpoints/device-profile.yml

There were some mistakes and missing endpoints in the v1 openapi doc.
- Have you connected this PR to the issue it resolves? #370 
- Does the documentation need an update? included
- Have you added unit or functional tests for this PR? No

Openapi doc fixes.

---

website/pages/en/index.js
website/siteConfig.js
website/static/css/custom.css
website/static/js/cookie-banner.js

Adds a cookie banner to the docs website.
No
Run docs website locally
- Have you connected this PR to the issue it resolves? #376 
- Does the documentation need an update? No
- Does this add new dependencies? NO
- Have you added unit or functional tests for this PR? NO

Add cookie banner.

---

app/networkProtocols/handlers/LoraOpenSource/LoraOpenSourceRestClient.js
bin/clean.js
development/chirpstack/configuration/mosquitto/mosquitto.conf
development/chirpstack/docker-compose.yml
package-lock.json
test/networks/lora-v2.js

It fixes the CI E2E test that was failing.  
No
Verify the Travis CI process test passes
1.  The docker container names of the chirp stack changed so that had to be updated
2. The Database conatiner names changed so the clean wasn't working fully before the test
3. Lora 2.0 app server switched login to use email rather than username so that was also fixed 
lpwanserver_dev_e2e_test |   209 passing (17s)
lpwanserver_dev_e2e_test |   22 pending
lpwanserver_dev_e2e_test | 
lpwanserver_dev_e2e_test exited with code 
- No this is a premerge to then merge the automated update branches
- No
- No
- Not added but …

Fix the CI test
